#!/bin/sh

format='%Y-%m-%d_%H-%M-%S'
dir="$(xdg-user-dir PICTURES)"
file="$dir/$(date +"$format")_grim.png"

grim -g "$(slurp)" "$file" &&
    notify-send "Screenshot saved" "$file" &&
    wl-copy --type image/png < "$file"
