#!/bin/bash
sink_string=$(pactl list sinks | grep "Name: ")

delimiter="Name: "

string=$sink_string$delimiter

sink_array=()
while [[ $string ]]; do
 sink_array+=( "${string%%"$delimiter"*}" )
 string=${string#*"$delimiter"}
done

sinks=[]
index=0
for sink in ${sink_array[@]}
do
  if [[ ! $sink == "name:" ]]
  then
    echo $index "$sink"
    sinks[$index]=$sink
    index=$((index+1))
  fi
done

read -p "Sink index: " -n 1 -r
echo

pactl set-default-sink "${sinks[$REPLY]}"
