
[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.95

[general]
import = [
    "~/.config/alacritty/themes/catppuccin-frappe.toml"
]
