input "type:keyboard" {
    xkb_layout us,fi
    xkb_options grp:win_space_toggle,compose:caps
    repeat_rate 30
    repeat_delay 250
}

input "type:touchpad" {
    dwt enabled
    tap enabled
    drag_lock disabled
    natural_scroll disabled
    middle_emulation disabled
}
